# * * * * * *
# | | | | | |
# | | | | | +-- Year              (range: 1900-3000)
# | | | | +---- Day of the Week   (range: 1-7, 1 standing for Monday)
# | | | +------ Month of the Year (range: 1-12)
# | | +-------- Day of the Month  (range: 1-31)
# | +---------- Hour              (range: 0-23)
# +------------ Minute            (range: 0-59)

rss_feeds:
  cron: "*/15 * * * *"
  class: RssFeeds
  args:
  description: "Store RSS feed entries every 15 min"

facebook_events:
  cron: "0 22 * * *"
  class: FacebookEvents
  args:
  description: "Store facebook events from graph api daily"

facebook_albums:
  cron: "0 22 * * *"
  class: FacebookAlbums
  args:
  description: "Store facebook albums from graph api daily"